### ISSUE TITLE
Template project repo?

### ISSUE THREAD

**Issue by greatfireball** [HackyHour/HackyHour.github.io#3]
Should we add a template repo as basis for new Hackyhour locations?

Opinions @iimog ?

**Comment by iimog** [comment]
Sure, why not. We could strip down the Wuerzburg version and introduce placeholders instead of the actual date/time/location/topic. This way everyone interested can get something up and running quickly. If they want something special they can still decide to do it from scratch (or use another template).

**Comment by greatfireball** [comment]
Who will be responsible?

Maybe I have some minutes tonight

**Comment by iimog** [comment]
If you have that would be welcome. I can then review tomorrow morning. Otherwise I will do it and have you review it when you find time :smiley:

**Comment by greatfireball** [comment]
Okay... Prepared a template. Feel free to review it @iimog

**Comment by iimog** [comment]
Thanks @greatfireball, it looks good so far. However, I'd like to add a README to the master branch describing how to use the template (e.g. that all website related stuff has to go into the `gh-pages` branch). Additionally I would replace the Würzburg flavored HackyHour logo with the generic one.

**Comment by greatfireball** [comment]
Thx for commenting. Will add both later

**Comment by iimog** [comment]
I swapped the default logo and set `gh-pages` as the default branch. I also converted the repo to a template repository.
